# Generated by Django 3.2.8 on 2021-10-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_on_boarded',
            field=models.BooleanField(default=False),
        ),
    ]
