# Generated by Django 3.2.8 on 2021-10-14 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name format is invalid', regex="^([ \\u00c0-\\u01ffa-zA-Z'\\-])+$")]),
        ),
    ]
