# Generated by Django 3.2.8 on 2021-10-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211015_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('INACTIVE', 'InActive')], default='ACTIVE', max_length=9),
        ),
    ]
